### ISSUE TITLE
Ignore static agents that are not sufficient for pending workload

### ISSUE THREAD

**Issue by xoxys** [woodpecker-ci/autoscaler#133]
If static agents with free capacities exist, but the agents cannot process pending workload due to their configuration, e.g. due to labels, the autoscaler still does not create any agents.

**Comment by xoxys** [comment]
Checked again, this setup definitely causes problems.

**Comment by pat-s** [comment]
Can confirm, had a static agent with workloads for amd64 and the autoscaler with a filter for arm64. The latter only kicked in once the static agent was removed.
