### ISSUE TITLE
Support other OS than Debian ones

### ISSUE THREAD

**Issue by pat-s** [woodpecker-ci/autoscaler#165]
Currently the installation of docker is hardcoded to apt-based distributions: https://github.com/woodpecker-ci/autoscaler/blob/88577b83ea0ccaa3d53a6c9acf61392c8b16f471/engine/const.go#L24-L29

**Comment by anbraten** [comment]
What would be your usecase for some other os?

**Comment by pat-s** [comment]
I just prefer rhel-based ones over debian-based ones.

There is already `WOODPECKER_HETZNERCLOUD_IMAGE` which is only limited to a few options due to the mentioned restrictions.

Ideally, the correct cloud-init template would be chosen based on the selected `WOODPECKER_HETZNERCLOUD_IMAGE`.

**Comment by xoxys** [comment]
I don't think we should add built-in cloud-init templates for multiple distributions. It's already possible to overwrite the cloud-init templates by users, why not just use it?

**Comment by pat-s** [comment]
Fair enough, didn't see that this was configurable. Thanks @xoxys!
