### ISSUE TITLE
Publish semver images

### ISSUE THREAD

**Issue by pat-s** [woodpecker-ci/autoscaler#166]
Currently, only `next` is published: https://hub.docker.com/r/woodpeckerci/autoscaler/tags

**Comment by anbraten** [comment]
It's still pretty experimental, so I avoided to do an actual release yet

**Comment by xoxys** [comment]
Then we should stop tagging GH releases... Having SemVer GH releases but no container images is confusing. Nevertheless, we should just push tagged images, experimental or not, that's what 0.x.x versions are made for

**Comment by anbraten** [comment]
We could test the latest changes for 1-2 weeks now, solve #164 and release the next version #117 after that.

**Comment by xoxys** [comment]
As I said, 0.x is for development/experimental versions. I don't see why we are still afraid of releases.

**Comment by pat-s** [comment]
I second @xoxys opinion. If there's an issue, just release a patch release (?). 

The release helper makes the process almost seamless.

**Comment by pat-s** [comment]
Actually, everything is already in place to publish semver, I think the files were added after the last release. So the next one should publish a semver image as well. 

Looking at the pending changelog, it might be time to release a new version?

**Comment by anbraten** [comment]
The new version seems to work quite well from what I saw and finally feels to be kinda smart.

**Comment by xoxys** [comment]
Fixed since v0.3.0
