### ISSUE TITLE
Return errors during cloud-init

### ISSUE THREAD

**Issue by pat-s** [woodpecker-ci/autoscaler#167]
Which prevent docker to be installed and the agent coming up. E.g. I just had this one here:

```
2024-07-06 19:37:31,783 - util.py[DEBUG]: Attempting to load yaml from string of length 1215 with allowed root types (<class 'dict'>,)
2024-07-06 19:37:31,785 - util.py[WARNING]: Failed loading yaml blob. Invalid format at line 41 column 1: "while scanning a simple key
  in "<unicode string>", line 41, column 1:
    WOODPECKER_TOKEN=eyJhbGciOiJIUzI ...
    ^
```

After setting

```
          env:
            - name: WOODPECKER_AGENT_ENV
              value: |
                WOODPECKER_SERVER=XYZ
                WOODPECKER_TOKEN=XYZ
```

**Comment by xoxys** [comment]
How should that work? In worst case, not a single wp component is running on the machine if cloud-init failed. What should be returned and where?

**Comment by anbraten** [comment]
Similar to #153. 

I think the general issue is getting some feedback why an agent is not working currently requires manual interaction with the cloud provider or sshing into the agent, so some kind of feedback system would be awesome. 

(How this could be implemented easily, but also in a robust and secure way. I've no idea atm 🤷🏾‍♂️)

**Comment by xoxys** [comment]
Admins should be able to log in to a faulty agent and just read the syslog.
