### ISSUE TITLE
Question about metric’s 

### ISSUE THREAD

**Issue by gedw99** [woodpecker-ci/autoscaler#2]
This looks really good.

it’s booting physical servers on hertzner ?

Is it in production? 

1. 
I don’t see any metrics to allow it to see if it should kill a server. Maybe that’s in the woodpecker agent where it is probably just watching cpu / memory and disk usage ? 

2. 
Another thing I wonder is about rebalancing. 

You have for example : 

3 servers

1 server is using 5% cpu and the other 2 servers are using 60 and 70% respectively. 

The system should then startup the workers on server 1 on server 3, and kill server 1.  You just saved money :)

Hertzner does not allow shared volumes so you must kill server 1 first to release the volume and then start the same users workload on server 3.

so then to avoid down time for all users in Server 1 you normally need a message queue to buffer all requests , while the change over happens. 

Please let me know what is what etc and I can then help where needed.

I suspect we need a global job runner / manager to do the rebalancing use case …

**Comment by anbraten** [comment]
Yes its booting VPSs on Hetzner Cloud. We use one autoscaler for the Woodpecker project itself <https://ci.woodpecker-ci.org>, but its not heavily tested yet.

The server provides a queue list of the amount of pending workflows, running workflows, and workflows waiting for other workflows. In addition it provides a list of all agents and the amount / ids of workflows which they are currently running.

The autoscaler simply looks at the amount of workflows todo and the capacity it currently has by multiplying agents * workflows-per-agent. It then decides to add or remove the max/min configured amount of agents. Removing is done by setting the do-not-take-new-workflows flag and removing the agent once it finished all running workflows.

Its a pretty simple logic which expects that workflows normally need a similar amount of resources, but works pretty well for most common scenarios without any extra config needed IMO.

**Comment by gedw99** [comment]
hey @anbraten 

thanks for the explanation.  

ah i thought robot gives you a physical server, but it's just a VM, so shared with others ?

So there its lights out operation ? you don't have to touch it and it will scale up and down as needed ?

It would be better if we measure RAM and CPU, and when it gets beyond some threshold ( typically 75% ) we boot another.
And also when its gets below 20%, stop taking new jobs, and kill itself ?

**Comment by gedw99** [comment]
been looking at the code, and maybe https://github.com/choria-io/asyncjobs is better for managing large fleets ?

i use this currently, and it can handle 1,000's of servers.

**Comment by xoxys** [comment]
I don't think there is a real benefit of using any kind of async task handler in our case. @anbraten What do you think? Should we close this one?

**Comment by anbraten** [comment]
Potentially managing 1000s agents should probably be no problem with the current autoscaler as it will just call apis. If we get to a bottelneck it will probably be the server managing 1000 incoming agent connections, although that's presumably no issue as well if not millions of logs are send.
