### ISSUE TITLE
Agents are removed even though they have tasks assigned

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/autoscaler#50]
This happens pretty often on ci.woodpecker-ci.org.
Agents are removed, even though there are tasks assigned to them (you can see this in the queue admin tab). The tasks have not started yet though.

Example (until it's canceled or restarted): https://ci.woodpecker-ci.org/repos/3780/pipeline/9626 (`docker` and `securityscan`)

**Comment by xoxys** [comment]
Yes have seen this too. IMO this is a server issue. The problem is, for the autoscaler the `waiting on dependencies` status is excluded but the server won't move item from  `waiting on dependencies` to e.g. `pending` without an available agent for whatever reason.

**Comment by xoxys** [comment]
Might be (partially) related to https://github.com/woodpecker-ci/woodpecker/issues/2685

**Comment by runephilosof-karnovgroup** [comment]
The draining is not working [agent option "stop agent from taking new tasks" not working](https://github.com/woodpecker-ci/woodpecker/issues/1990)
So a task might be given to an agent just before it shuts down.
